# -----------------------------------------------------------------------------
# Kind Multi-Node Cluster Configuration (1 Control-Plane + 3 Workers)
# -----------------------------------------------------------------------------
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Ingress Nginx / App Access
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP

      # ArgoCD UI
      - containerPort: 30082
        hostPort: 30082
        protocol: TCP

      # Grafana Dashboard
      - containerPort: 30030
        hostPort: 30030
        protocol: TCP

      # Prometheus Server
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP

  - role: worker
  - role: worker
  - role: worker